/* Autogenerated, do not edit */
#ifndef __CR_VERSION_H__
#define __CR_VERSION_H__
#define CRIU_VERSION "3.15"
#define CRIU_VERSION_MAJOR  3
#define CRIU_VERSION_MINOR  15
#define CRIU_GITID "v3.14-534-g2cf0b2915"
#endif /* __CR_VERSION_H__ */
