/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: bpfmap-data.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "bpfmap-data.pb-c.h"
void   bpfmap_data_entry__init
                     (BpfmapDataEntry         *message)
{
  static BpfmapDataEntry init_value = BPFMAP_DATA_ENTRY__INIT;
  *message = init_value;
}
size_t bpfmap_data_entry__get_packed_size
                     (const BpfmapDataEntry *message)
{
  assert(message->base.descriptor == &bpfmap_data_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bpfmap_data_entry__pack
                     (const BpfmapDataEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bpfmap_data_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bpfmap_data_entry__pack_to_buffer
                     (const BpfmapDataEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bpfmap_data_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BpfmapDataEntry *
       bpfmap_data_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BpfmapDataEntry *)
     protobuf_c_message_unpack (&bpfmap_data_entry__descriptor,
                                allocator, len, data);
}
void   bpfmap_data_entry__free_unpacked
                     (BpfmapDataEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &bpfmap_data_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor bpfmap_data_entry__field_descriptors[4] =
{
  {
    "map_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BpfmapDataEntry, map_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keys_bytes",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BpfmapDataEntry, keys_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values_bytes",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BpfmapDataEntry, values_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BpfmapDataEntry, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bpfmap_data_entry__field_indices_by_name[] = {
  3,   /* field[3] = count */
  1,   /* field[1] = keys_bytes */
  0,   /* field[0] = map_id */
  2,   /* field[2] = values_bytes */
};
static const ProtobufCIntRange bpfmap_data_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor bpfmap_data_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bpfmap_data_entry",
  "BpfmapDataEntry",
  "BpfmapDataEntry",
  "",
  sizeof(BpfmapDataEntry),
  4,
  bpfmap_data_entry__field_descriptors,
  bpfmap_data_entry__field_indices_by_name,
  1,  bpfmap_data_entry__number_ranges,
  (ProtobufCMessageInit) bpfmap_data_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
