/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: img-streamer.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "img-streamer.pb-c.h"
void   img_streamer_request_entry__init
                     (ImgStreamerRequestEntry         *message)
{
  static ImgStreamerRequestEntry init_value = IMG_STREAMER_REQUEST_ENTRY__INIT;
  *message = init_value;
}
size_t img_streamer_request_entry__get_packed_size
                     (const ImgStreamerRequestEntry *message)
{
  assert(message->base.descriptor == &img_streamer_request_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t img_streamer_request_entry__pack
                     (const ImgStreamerRequestEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &img_streamer_request_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t img_streamer_request_entry__pack_to_buffer
                     (const ImgStreamerRequestEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &img_streamer_request_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ImgStreamerRequestEntry *
       img_streamer_request_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ImgStreamerRequestEntry *)
     protobuf_c_message_unpack (&img_streamer_request_entry__descriptor,
                                allocator, len, data);
}
void   img_streamer_request_entry__free_unpacked
                     (ImgStreamerRequestEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &img_streamer_request_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   img_streamer_reply_entry__init
                     (ImgStreamerReplyEntry         *message)
{
  static ImgStreamerReplyEntry init_value = IMG_STREAMER_REPLY_ENTRY__INIT;
  *message = init_value;
}
size_t img_streamer_reply_entry__get_packed_size
                     (const ImgStreamerReplyEntry *message)
{
  assert(message->base.descriptor == &img_streamer_reply_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t img_streamer_reply_entry__pack
                     (const ImgStreamerReplyEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &img_streamer_reply_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t img_streamer_reply_entry__pack_to_buffer
                     (const ImgStreamerReplyEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &img_streamer_reply_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ImgStreamerReplyEntry *
       img_streamer_reply_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ImgStreamerReplyEntry *)
     protobuf_c_message_unpack (&img_streamer_reply_entry__descriptor,
                                allocator, len, data);
}
void   img_streamer_reply_entry__free_unpacked
                     (ImgStreamerReplyEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &img_streamer_reply_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor img_streamer_request_entry__field_descriptors[1] =
{
  {
    "filename",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ImgStreamerRequestEntry, filename),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned img_streamer_request_entry__field_indices_by_name[] = {
  0,   /* field[0] = filename */
};
static const ProtobufCIntRange img_streamer_request_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor img_streamer_request_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "img_streamer_request_entry",
  "ImgStreamerRequestEntry",
  "ImgStreamerRequestEntry",
  "",
  sizeof(ImgStreamerRequestEntry),
  1,
  img_streamer_request_entry__field_descriptors,
  img_streamer_request_entry__field_indices_by_name,
  1,  img_streamer_request_entry__number_ranges,
  (ProtobufCMessageInit) img_streamer_request_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor img_streamer_reply_entry__field_descriptors[1] =
{
  {
    "exists",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ImgStreamerReplyEntry, exists),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned img_streamer_reply_entry__field_indices_by_name[] = {
  0,   /* field[0] = exists */
};
static const ProtobufCIntRange img_streamer_reply_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor img_streamer_reply_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "img_streamer_reply_entry",
  "ImgStreamerReplyEntry",
  "ImgStreamerReplyEntry",
  "",
  sizeof(ImgStreamerReplyEntry),
  1,
  img_streamer_reply_entry__field_descriptors,
  img_streamer_reply_entry__field_indices_by_name,
  1,  img_streamer_reply_entry__number_ranges,
  (ProtobufCMessageInit) img_streamer_reply_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
