/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pidns.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "pidns.pb-c.h"
void   pidns_entry__init
                     (PidnsEntry         *message)
{
  static PidnsEntry init_value = PIDNS_ENTRY__INIT;
  *message = init_value;
}
size_t pidns_entry__get_packed_size
                     (const PidnsEntry *message)
{
  assert(message->base.descriptor == &pidns_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pidns_entry__pack
                     (const PidnsEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pidns_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pidns_entry__pack_to_buffer
                     (const PidnsEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pidns_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PidnsEntry *
       pidns_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PidnsEntry *)
     protobuf_c_message_unpack (&pidns_entry__descriptor,
                                allocator, len, data);
}
void   pidns_entry__free_unpacked
                     (PidnsEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pidns_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pidns_entry__field_descriptors[1] =
{
  {
    "ext_key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PidnsEntry, ext_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pidns_entry__field_indices_by_name[] = {
  0,   /* field[0] = ext_key */
};
static const ProtobufCIntRange pidns_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor pidns_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pidns_entry",
  "PidnsEntry",
  "PidnsEntry",
  "",
  sizeof(PidnsEntry),
  1,
  pidns_entry__field_descriptors,
  pidns_entry__field_indices_by_name,
  1,  pidns_entry__number_ranges,
  (ProtobufCMessageInit) pidns_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
