/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: apparmor.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "apparmor.pb-c.h"
void   aa_policy__init
                     (AaPolicy         *message)
{
  static AaPolicy init_value = AA_POLICY__INIT;
  *message = init_value;
}
size_t aa_policy__get_packed_size
                     (const AaPolicy *message)
{
  assert(message->base.descriptor == &aa_policy__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aa_policy__pack
                     (const AaPolicy *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aa_policy__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aa_policy__pack_to_buffer
                     (const AaPolicy *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aa_policy__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AaPolicy *
       aa_policy__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AaPolicy *)
     protobuf_c_message_unpack (&aa_policy__descriptor,
                                allocator, len, data);
}
void   aa_policy__free_unpacked
                     (AaPolicy *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &aa_policy__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   aa_namespace__init
                     (AaNamespace         *message)
{
  static AaNamespace init_value = AA_NAMESPACE__INIT;
  *message = init_value;
}
size_t aa_namespace__get_packed_size
                     (const AaNamespace *message)
{
  assert(message->base.descriptor == &aa_namespace__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aa_namespace__pack
                     (const AaNamespace *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aa_namespace__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aa_namespace__pack_to_buffer
                     (const AaNamespace *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aa_namespace__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AaNamespace *
       aa_namespace__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AaNamespace *)
     protobuf_c_message_unpack (&aa_namespace__descriptor,
                                allocator, len, data);
}
void   aa_namespace__free_unpacked
                     (AaNamespace *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &aa_namespace__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   apparmor_entry__init
                     (ApparmorEntry         *message)
{
  static ApparmorEntry init_value = APPARMOR_ENTRY__INIT;
  *message = init_value;
}
size_t apparmor_entry__get_packed_size
                     (const ApparmorEntry *message)
{
  assert(message->base.descriptor == &apparmor_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t apparmor_entry__pack
                     (const ApparmorEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &apparmor_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t apparmor_entry__pack_to_buffer
                     (const ApparmorEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &apparmor_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ApparmorEntry *
       apparmor_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ApparmorEntry *)
     protobuf_c_message_unpack (&apparmor_entry__descriptor,
                                allocator, len, data);
}
void   apparmor_entry__free_unpacked
                     (ApparmorEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &apparmor_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor aa_policy__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AaPolicy, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blob",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(AaPolicy, blob),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aa_policy__field_indices_by_name[] = {
  1,   /* field[1] = blob */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange aa_policy__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor aa_policy__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "aa_policy",
  "AaPolicy",
  "AaPolicy",
  "",
  sizeof(AaPolicy),
  2,
  aa_policy__field_descriptors,
  aa_policy__field_indices_by_name,
  1,  aa_policy__number_ranges,
  (ProtobufCMessageInit) aa_policy__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor aa_namespace__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AaNamespace, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "policies",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(AaNamespace, n_policies),
    offsetof(AaNamespace, policies),
    &aa_policy__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "namespaces",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(AaNamespace, n_namespaces),
    offsetof(AaNamespace, namespaces),
    &aa_namespace__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aa_namespace__field_indices_by_name[] = {
  0,   /* field[0] = name */
  2,   /* field[2] = namespaces */
  1,   /* field[1] = policies */
};
static const ProtobufCIntRange aa_namespace__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor aa_namespace__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "aa_namespace",
  "AaNamespace",
  "AaNamespace",
  "",
  sizeof(AaNamespace),
  3,
  aa_namespace__field_descriptors,
  aa_namespace__field_indices_by_name,
  1,  aa_namespace__number_ranges,
  (ProtobufCMessageInit) aa_namespace__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor apparmor_entry__field_descriptors[1] =
{
  {
    "namespaces",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ApparmorEntry, n_namespaces),
    offsetof(ApparmorEntry, namespaces),
    &aa_namespace__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned apparmor_entry__field_indices_by_name[] = {
  0,   /* field[0] = namespaces */
};
static const ProtobufCIntRange apparmor_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor apparmor_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "apparmor_entry",
  "ApparmorEntry",
  "ApparmorEntry",
  "",
  sizeof(ApparmorEntry),
  1,
  apparmor_entry__field_descriptors,
  apparmor_entry__field_indices_by_name,
  1,  apparmor_entry__number_ranges,
  (ProtobufCMessageInit) apparmor_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
