/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: timens.proto */

#ifndef PROTOBUF_C_timens_2eproto__INCLUDED
#define PROTOBUF_C_timens_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Timespec Timespec;
typedef struct _TimensEntry TimensEntry;


/* --- enums --- */


/* --- messages --- */

struct  _Timespec
{
  ProtobufCMessage base;
  uint64_t tv_sec;
  uint64_t tv_nsec;
};
#define TIMESPEC__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&timespec__descriptor) \
    , 0, 0 }


struct  _TimensEntry
{
  ProtobufCMessage base;
  Timespec *monotonic;
  Timespec *boottime;
};
#define TIMENS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&timens_entry__descriptor) \
    , NULL, NULL }


/* Timespec methods */
void   timespec__init
                     (Timespec         *message);
size_t timespec__get_packed_size
                     (const Timespec   *message);
size_t timespec__pack
                     (const Timespec   *message,
                      uint8_t             *out);
size_t timespec__pack_to_buffer
                     (const Timespec   *message,
                      ProtobufCBuffer     *buffer);
Timespec *
       timespec__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   timespec__free_unpacked
                     (Timespec *message,
                      ProtobufCAllocator *allocator);
/* TimensEntry methods */
void   timens_entry__init
                     (TimensEntry         *message);
size_t timens_entry__get_packed_size
                     (const TimensEntry   *message);
size_t timens_entry__pack
                     (const TimensEntry   *message,
                      uint8_t             *out);
size_t timens_entry__pack_to_buffer
                     (const TimensEntry   *message,
                      ProtobufCBuffer     *buffer);
TimensEntry *
       timens_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   timens_entry__free_unpacked
                     (TimensEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Timespec_Closure)
                 (const Timespec *message,
                  void *closure_data);
typedef void (*TimensEntry_Closure)
                 (const TimensEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor timespec__descriptor;
extern const ProtobufCMessageDescriptor timens_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_timens_2eproto__INCLUDED */
